### ISSUE TITLE
No entrypoint.sh file for Docker build

### ISSUE THREAD

**Issue by Lokarde** [vteams/open-source-billing#101]
There is no entrypoint.sh file for build docker image from dockerfile so the build fail
![Capture du 2020-02-13 14-59-30](https://user-images.githubusercontent.com/29501567/74442305-8e117080-4e71-11ea-94c4-e1a3705aaec9.png)

**Comment by shahzadtariq-nxb** [comment]
entrypoint.sh file included in latest commit
