### ISSUE TITLE
Can't install gem rmagick -v '2.13.4'

### ISSUE THREAD

**Issue by Tepira** [vteams/open-source-billing#17]
checking for gcc... yes
checking for Magick-config... no
checking for pkg-config... yes

I cant install gem install rmagick -v '2.13.4' even with sudo apt-get install graphicsmagick-libmagick-dev-compat.

**Comment by umairmunir40** [comment]
"rmagick" requires "imagemagick" to be installed on your machine.....
So first try  this command to install "imagemagick" on your machine......
            sudo apt-get install imagemagick
then try "bundle install"  command to install gems...
this will work...

**Comment by musamamasood** [comment]
thanks.
