### ISSUE TITLE
Ruby 1.9.2 - excuse me, what?!

### ISSUE THREAD

**Issue by benkoller** [vteams/open-source-billing#18]
Hi,

I have to say I'm a little surprised to see ruby 1.9.2 stated as requirement when you list stuff like Zapata and other gems in  your gemfile that clearly require ruby >= 2.

Am I missing something entirely or how could this mismatch happen?

**Comment by shahzad-nxb** [comment]
Hi Benkoller, 

OSB was built using ruby 1.9.2 and rails 3.2 but we have recently updated it to ruby 2.0.0 and rails 4.1.8 along with many other new features like multicurrency, internationalization, enhanced reporting, restful API's and fixed issues we find while regression testing.

We are currently working on few more interesting features alongwith updated installation guide/README. We will update that to github ASAP.

We apologies for inconvenience.
