### ISSUE TITLE
Deprecated Modules ?!

### ISSUE THREAD

**Issue by suther** [vteams/open-source-billing#22]
I got this message after I've finished bundle install: 

> Your bundle is complete!
It was installed into ./vendor/bundle
Post-install message from bcrypt-ruby:

>#######################################################

>The bcrypt-ruby gem has changed its name to just bcrypt.  Instead of
installing `bcrypt-ruby`, you should install `bcrypt`.  Please update your
dependencies accordingly.

>#######################################################

>Post-install message from hashie_rails:
!    The 'hashie_rails' gem has been deprecated and has been replaced by 'hashie-forbidden_attributes'.
!    See: https://rubygems.org/gems/hashie-forbidden_attributes
!    And: https://github.com/Maxim-Filimonov/hashie-hashie-forbidden_attributes
Post-install message from money:
Please note the following API changes in Money version 6

> - Money#amount, Money#dollars methods now return instances of BigDecimal (rather than Float).

>Please read the migration notes at https://github.com/RubyMoney/money#migration-notes
and choose the migration that best suits your application.

>Test responsibly :-)
Post-install message from twitter-bootstrap-rails:
Important: You may need to add a javascript runtime to your Gemfile in order for bootstrap's LESS files to compile to CSS. 

>**********************************************

Maybe this helps for the future development.
I use ruby 2.2

**Comment by imranmalik** [comment]
@suther thanks for posting these warning. We have tested OSB with Ruby 2.0. We'll look into above warning and try to fix them.
