### ISSUE TITLE
Production-DB was not created during installprocess

### ISSUE THREAD

**Issue by suther** [vteams/open-source-billing#23]
I have installed OSB. The production-logs tell me that there is no Database.
I have set the database-servers in database.yml all to the same host (localhost) with same Password.

Even If I run:
>  rake db:create db:migrate

I got only the message for development and test: 
osb_development already exists
osb_test already exists
> /var/www/open-source-billing/vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::PDF
/var/www/open-source-billing/vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of PDF was here

**Comment by bitbox** [comment]
You may try using the following before accessing the application in rpoduction:
```
RAILS_ENV=production rake db:create
RAILS_ENV=production rake db:schema:load
RAILS_ENV=production bundle exec rake assets:precompile
```

Also, I note you are getting a warning I also got:
> warning: already initialized constant Mime::PDF

To avoid this warning I commented last line (8) from **config/initializers/mime_types.rb**
```
# Be sure to restart your server when you modify this file.

# Add new mime types for use in respond_to blocks:
# Mime::Type.register "text/richtext", :rtf
# Mime::Type.register_alias "text/html", :iphone
Mime::Type.register "application/xls", :xls
Mime::Type.register "application/xlsx", :xlsx
#Mime::Type.register "application/pdf", :pdf
```

**Comment by shahzad-nxb** [comment]
As @bitbox explained, you need to specify your environment with rake commands. So run following commands from command line in the given order

    RAILS_ENV=production rake db:create
    RAILS_ENV=production rake db:migrate

And then to seed database with system defaults

    RAILS_ENV=production rake db:seed

To precompile assets

    RAILS_ENV=production bundle exec rake assets:precompile
