### ISSUE TITLE
default installation exposes invoices

### ISSUE THREAD

**Issue by raomin** [vteams/open-source-billing#26]
The links to the invoices includes an encrypted `invoice_id`. Successfully decrypting the encrypted `invoice_id` authenticate the link; then the invoice is displayed.

**Issue:**
The encrypt/decrypt methods uses an fixed string `yourpass` as secret. If this string is not changed, then it is trivial to generate `invoice_id` and access all invoices in a system, in anonymous access.

**Suggestion:**
This string should be part of `config/initializers/config.rb` and one step of the installation process should be to change it.

**Comment by Umair-Munir** [comment]
We have fixed this in release v1.0
