### ISSUE TITLE
No access control on pdf invoices

### ISSUE THREAD

**Issue by raomin** [vteams/open-source-billing#27]
The preview of invoices (accessible anonymously) displays the invoice and allows to download a PDF of invoices. This HTML preview is authenticated with an encrypted invoice_id.
However, the PDF link is NOT authenticated, the invoice_id is in clear.

Therefore **all invoices data are anonymously accessible in their PDF version** with this URL:
`/invoices/invoice_pdf/[InvoiceID].pdf`

This controller should use the same authentication method as the html preview.

**Comment by Umair-Munir** [comment]
This feature has been implemented in release  v1.0
