### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ninjatrench** [vteams/open-source-billing#29]
Amazing work on Open Source billing. I just loved it by looking at the demo
It is about to save a lot of money for my startup.

While installing I am facing following problems :

I clone'd the repo and while doing bundle install it gives following error :

Gem files will remain installed in /var/lib/gems/1.9.1/gems/mysql-2.9.1 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/mysql-2.9.1/ext/mysql_api/gem_make.out
An error occurred while installing mysql (2.9.1), and Bundler cannot continue.
Make sure that `gem install mysql -v '2.9.1'` succeeds before bundling.

I have mysql-server installed on my system.

system conf :
Linux myhost 3.13.0-46-generic #75-Ubuntu SMP Tue Feb 10 15:24:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"

can you help me solve this ?
or if you can send list of bash commands to be executed on plain ubuntu server from scratch then it would be best.

thanks.

**Comment by sarwan-nxb** [comment]
@ninjatrench Thanks for you interest in OSB. It looks like you have missed mySQL client library. First install this library by using following command and then run `bundle install`. 
`sudo apt-get install mysql-client libmysqlclient-dev`
Hopefully, This issue will be resolved.

**Comment by ninjatrench** [comment]
@sarwan-nxb Thanks alot. 
it seems perfect.
