### ISSUE TITLE
How to install on hostgator server?

### ISSUE THREAD

**Issue by shobzz87** [vteams/open-source-billing#30]
I have 2 options:
1, Ruby Gem Installer
2, Manage Your Ruby on Rails Applications

Under Options 1:
Use Your Modules
Rails version 3.0 is not currently supported and can cause a broken Ruby on Rails environment.
Add “/home4/user/ruby/gems” to the include path.
$:.push("/home4/user/ruby/gems")

Find a Module _________ Search
show available modules>https://rubygems.org/gems/-
Install a Module ______________ install Now

??? Can you please let me know. where to place that downloaded >uploaded >extracted files and folders

How to Link? is it called as ruby module(gem) ?

**Comment by nazarhussain** [comment]
We had not used Hostgator service before. Does it allow you ssh access to your VPS Server? Or you are using their Shared Hosting?

**Comment by shobzz87** [comment]
Hi m using shared hosting, But it supports ruby.

**Comment by sarwan-nxb** [comment]
OpenSourceBilling is built in Rails 4.1 with ruby 2.0. So, if your server supports ruby 2.0 then you can install OpenSourceBilling. Otherwise, contact your hosting server to update ruby version.

**Comment by rajuparsha** [comment]
Hello Guys,

I have install OpenSourceBilling in CentOS which supports Rails4.1.8 and also Ruby 2.1.5, How to use and publish web pages of ruby . Please Guide me.

**Comment by sarwan-nxb** [comment]
@rajuparsha 
Thanks for your interest in OpenSourceBilling. Could you please elaborate, what do you meant by publish web pages?

**Comment by rajuparsha** [comment]
We want to implement this package in our web servers and want to know more about this software. Whether is it OpenSourced or paid?. Whether we can opt for support for this package.

**Comment by sarwan-nxb** [comment]
Yes, this is open source. For further details of basic setup and custom requirements visit this link `http://opensourcebilling.org/custom-requirements`

**Comment by FTLWIFI** [comment]
SSH is available on Hostgator 

SSH your dedicated ip address: port 2222 login is your cpanel login 

What are the steps to install the Gem Packages 

Thanks

**Comment by shahzad-nxvt** [comment]
First you need to install ruby (version > 1.9.3) on your server. After ruby installation, you can install required gems & configure application by following steps mentioned in readme file https://github.com/vteams/open-source-billing/blob/master/README.md

If you want us to install this software on your server, kindly visit http://opensourcebilling.org/custom-requirements/ for details of packages we offer for installation.
