### ISSUE TITLE
rake db:create failure: can't activate mysql2 | already activated

### ISSUE THREAD

**Issue by iamra** [vteams/open-source-billing#31]
Hi, Thanks for a GREAT product.
Does anyone have any advice on what is causing the following to fail?
I prefer to install into mysql.
I have copied the ./config/database.yml.backup into ./config/database.yml
I included my root password. 
then I run `rake db:create`

I have mysql, as well as PostgreSQL installed.
I am on Ubuntu 14.04 with ruby 2.2.3 installed through rbenv/ruby-build

`
rake aborted!
Gem::LoadError: Specified 'mysql2' for database adapter, but the gem is not loaded. Add`gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).

Gem::LoadError: can't activate mysql2 (~> 0.3.13), already activated mysql2-0.4.2. Make sure all dependencies are added to Gemfile.

Tasks: TOP => db:create
`

Thank you for your time.

**Comment by imranmalik** [comment]
Please make sure you have installed mysql `sudo apt-get install mysql-server` and do a `bundle install` after installing the mysql. After you have successfully installed both then try creating the database `bundle exec rake db:create`

**Comment by ramielbarsoum** [comment]
Yes, I have mysql-server installed and ran the commands as you recommended again. I am getting still the same error message.
I have the following gems installed via `gem list`
mysql (2.9.1)
mysql2 (0.4.2)

should the root password be stored plaintext or hashed?

**Comment by sarwan-nxb** [comment]
@ramielbarsoum 
   Please run following commands in terminal, Hope your issue will be resolved.
  `sudo apt-get install libmysql-ruby libmysqlclient-dev`
  `sudo apt-get install libmysqlclient-dev`
  
 Here is the link for reference http://stackoverflow.com/questions/3608287/error-installing-mysql2-failed-to-build-gem-native-extension

**Comment by ramielbarsoum** [comment]
That article issue seems to be related to "Failed to build gem native extension."
Where as what I am gathering from the issue I am getting is the following:
`
Gem::LoadError: Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).

Gem::LoadError: can't activate mysql2 (~> 0.3.13), already activated mysql2-0.4.2. Make sure all dependencies are added to Gemfile.
`
However:
Your link helped find this:
http://www.ict4g.net/adolfo/notes/2015/11/11/please-install-activerecord-mysql2-adapter.html
which allowed me to update the following In the Gemfile: 
`gem "mysql2" "~> 0.3.20"`

The remainder of the installation instructions completed by running  rake db:create db:migrate

I do not see any index files for the app, and the documentation really does not include any futher steps.
I am new to using ruby rails. and this installation has been needing so much custom installation that I am considering no longer using the software.

Thank you all for your help, it truly is a very good software based on what I tried in the demo.

**Comment by imranmalik** [comment]
One of our team member can pair with your get it installed on your machine. Please let me know if you are still interested.

**Comment by shahzadtariq-nxb** [comment]
Issue has been closed due to non-activity since last 2 years. Kindly re-open and share your log in case you are or someone else is still facing this issue.
