### ISSUE TITLE
Heroku Installer?

### ISSUE THREAD

**Issue by williamrussellajb** [vteams/open-source-billing#34]
Any Guides or Heroku installers for this awesome app?

**Comment by mshahzadtariq** [comment]
By default, Heroku does't support MySql while OpenSourceBilling uses mysql as database server. To install it to heroku, you need to modify database.yml file in config folder and few sql queries in lib folder. After that you can deploy this heroku just like any other rails application (i.e. git push heroku master).

If you are not enough familiar with rails to apply above mentioned changes in code, please let us know and we can install it for you. For more details, please visit custom requirements section [http://opensourcebilling.org/custom-requirements/]

**Comment by nmenag** [comment]
Create a version with **Postgres**

**Comment by nmenag** [comment]
or use https://devcenter.heroku.com/articles/cleardb
