### ISSUE TITLE
Upgrad to ruby on rails version 4.* 

### ISSUE THREAD

**Issue by putheakhem** [vteams/open-source-billing#36]
Should be upgrade to latest version of ruby on rails

**Comment by shahzad-nxb** [comment]
It is already upgraded to rails v 4.1.8 . You can verify this from Gemfile (gem 'rails', '~> 4.1.8')

**Comment by putheakhem** [comment]
Other one question . how can I configure it on my own VPS

**Comment by shahzad-nxb** [comment]
Installation instructions are mentioned in readme file. After installation, you need to configure apache or nginx vhost to point web server.

We can also install and configure it on your server. For more information, kindly visit http://opensourcebilling.org/custom-requirements/
