### ISSUE TITLE
Company logos inaccessible

### ISSUE THREAD

**Issue by TimShaw61** [vteams/open-source-billing#37]
Added a company logo but it cannot be retrieved for display.
production log shows:

ActionController::RoutingError (No route matches [GET] "/uploads/company/logo/1/thumb_ox_brand1_pos.gif"):

Should there be an entry in routes.rb to allow this?

**Comment by shahzad-nxvt** [comment]
serve_static_files is set to false in production.rb file (config/environments/production.rb). You need to set this config parameter as true and than restart your server. It will fix this issue.

    config.serve_static_assets = true

We have noted down this issue and will be fixed in next release. Thanks for your valuable feedback.
