### ISSUE TITLE
Sort order of Client list pulldown in New Invoice form

### ISSUE THREAD

**Issue by TimShaw61** [vteams/open-source-billing#38]
When using the New Invoice or New Recurring Profile forms, the available clients are listed in a pulldown select field.  This field sorting is undefined but it would be much better to have the underlying query sort on Client name to make locating a client easier when dealing with a larger number of clients.   I assume this is a simple fix to the client model...please advise how this can be achieved

**Comment by TimShaw61** [comment]
I have hacked this by amending the following line in app/helpers/invoices_helper.rb where load_clients is defined:

clients = Company.find_by_id(id).clients.unarchived.map{|c| [c.organization_name, c.id, {type: 'company_level'}]}

to read:

clients = Company.find_by_id(id).clients.unarchived.order(organization_name: :asc).map{|c| [c.organization_name, c.id, {type: 'company_level'}]}

but I'm sure there will be a better way to do this...!

**Comment by shahzadtariq-nxb** [comment]
Thanks for your efforts. We'll update sort-order in next release. Looking forward to your contribution in the future.
