### ISSUE TITLE
Delayed jobs not working

### ISSUE THREAD

**Issue by TimShaw61** [vteams/open-source-billing#39]
How can I debug this?  I have templates setup and apparently correctly configured for First, Second and Third reminders just like the seed.db file shows but after I send out the invoices, no reminder emails are generated and sent.  The delayed_jobs task is running; the production log shows there are large numbers of SQL queries being performed  all the time on the delayed_jobs table but it's not obvious why these emails don't get produced - it's not clear how this part of the system is supposed to work

**Comment by derekprovance** [comment]
I'm having a similar issue, trying to hack the code to figure it out myself. I'll post back if I find anything.

**Comment by shahzadtariq-nxb** [comment]
Verify if mailer is configured properly and emails are working. Update code to latest release and try again. Kindly re-open if issue persists.
