### ISSUE TITLE
Installation documentation needs updating

### ISSUE THREAD

**Issue by BloodyIron** [vteams/open-source-billing#46]
I just spent about a day and a half trying to get OSB setup in a VM. I understand that vteams offers a paid service to install the software, but the documentation for installation is grossly inaccurate.

I'm not trying to steal business from vteams here, because I support the FOSS business model, but the documentation seriously needs to be updated, and I'm not even sure if my recommendations below are the most accurate advice, but it worked for me.

Firstly, it needs to be updated to be tested against Ubuntu 16.04. I had thought my first problem was because I was using 16.04, but it wasn't. I have it working in 16.04 with the same steps (with my outlined modifications).

Secondly, the instructions are broken in multiple areas, even when using 14.04. I'm going to outline what I remember of the steps I took to get a workable environment.
1. Some of the build steps require cmake, so "apt-get install cmake" is something I had to do at some point early.
2. I had to use ruby 2.1.8 as a bunch of the packages would not work with any lower version of ruby.
3. I had to manually configure the Gemlist to set mysql2 gem to '0.3.20' and make sure that version was setup. Not doing this prevented me from doing db:create and other steps at that point.
4. I had to copy the config.yml into place BEFORE I could complete "rake db:migrate" (this step is mentioned later in the documentation, but I had to do it earlier to actually make progress).
5. I may have to do db:migrate and db: seed a few times, but that might be because of #4, and a change of operations might improve this.
6. In the config/environments/ folder, I had to copy the files into .rb extensions so that the db functions would stop complaining. I assume this is something required, but _IS DOCUMENTED NOWHERE THAT I COULD FIND_.

I had to spend a lot of time on this just to get it working, installation documentation really needs to be tested more frequently than this.

**Comment by BloodyIron** [comment]
Also, if you are interested, I could help test the documentation from time to time, to see if it's accurate. Since this seems like a pretty sweet invoicing tool. It would be nice to make this more appealing for new clients :)

**Comment by thepreferrednerd** [comment]
I've found this issue as well just recently. In particular, I'm installing this on an existing webserver, so I'm not sure if that has impact on versioning, etc. but cmake is definitely required, upgrading ruby is definitely required, and not setting the mysql2 version in the Gemlist causes more errors.

I'm still recieving some errors relating to deprecated value names, but I'm not experienced enough in Ruby to debug these. I think they might be avoidable if the installation instructions were more explicit.

**Comment by shahzadtariq-nxb** [comment]
Installation document has been updated in last release. Kindly review and share suggestions/feedback.

**Comment by rogerdg** [comment]
I'm giving up on this software because the documentation still doesn't match the software version.
I tried using Debian 8, but too much is omitted from the install doc to make it possible for me to use this.

**Comment by BloodyIron** [comment]
Yeah I gave up on this shit over a year ago.
