### ISSUE TITLE
User access control

### ISSUE THREAD

**Issue by BloodyIron** [vteams/open-source-billing#48]
I can't find anything about user access control in the GUI, or in the project documentation.

I would like to have control over user access because I don't want all users created to have full access to functions. For example, I would like to have staff who can submit time, but not have the ability to delete companies or records.

If I'm missing info on this, please tell me how I'm wrong. Otherwise, can we get user access control please?

**Comment by shahzad-nxvt** [comment]
This feature is already under development and shall be released for public use in near future.

**Comment by shahzadtariq-nxb** [comment]
This feature was released in last release.
