### ISSUE TITLE
Support for VAT

### ISSUE THREAD

**Issue by Dorme** [vteams/open-source-billing#53]
Is it possible to implement VAT?
The VAT number is mandatory on every invoice in Belgium (for invoices to companies that have a VAT number)?
So the VAT number for your own company needs to be on it and also the VAT number of the client.
Maybe a verification of the VAT number entered is also possible? I've seen that functionality in other invoicing programs.

**Comment by shahzadtariq-nxb** [comment]
Thank you for suggestion. We are working on new release and try to introduce VAT numbers.
