### ISSUE TITLE
Set calendar to start on Monday

### ISSUE THREAD

**Issue by moritz89** [vteams/open-source-billing#57]
Would it be possible to create a localization setting to change the calendar's start day from Sunday to Monday? This is especially useful for those from the EU and other countries outside the US. This setting should be available regardless of which language is set.

The location where the calendar appears: http://localhost:3000/en/logs

**Comment by shahzadtariq-nxb** [comment]
Thank you @moritz89  for you interest and suggestion. We'll try to make calendar configurable from settings section in next release. Stay tuned for many more exciting features and user interface updates in next release.
