### ISSUE TITLE
Is there a Docker image available?

### ISSUE THREAD

**Issue by ovizii** [vteams/open-source-billing#58]
And if not would it be possible to get an official one?

**Comment by shahzadtariq-nxb** [comment]
There is no docker image currently available. Thanks for your suggestion, we'll try to build docker image with next release.

**Comment by alexanderadam** [comment]
Is there an official Docker image available nowadays? I [wasn't able to find one](https://hub.docker.com/search?q=open%20source%20billing&type=image).

And why was this issue closed before it was solved? This way no one is able to track this!?

**Comment by alexanderadam** [comment]
Now some [Docker files are available](https://github.com/vteams/open-source-billing/commit/24b0c6c634483e884c42440fd77e5a8731f98ba0#diff-4e5e90c6228fd48698d074241c2ba760).

So in theory it should be possible to [create a GitHub action to build and publish an image](https://www.prestonlamb.com/blog/creating-a-docker-image-with-github-actions).

Thank you for your work, @shahzadtariq-nxb / @mshahzadtariq.

**Comment by shahzadtariq-nxb** [comment]
You we working on Docker files to improve them further. Currently we are working on web server configuration (Nginx/Apache) with docker and after that we'll surely configure Github action

**Comment by alexanderadam** [comment]
Awesome news.
