### ISSUE TITLE
Dependency problems solved by adding PHP PPA

### ISSUE THREAD

**Issue by RyanHarrigan** [vteams/open-source-billing#59]
I am new to osb, but have found many dependency issues with the libmagick(core|wand)-dev libraries on install (using Ubuntu 16.04). All of the pecl libraries libmagick(core|wand)-dev needed were accessible from 

sudo add-apt-repository ppa:ondrej/php

which is a main php repository. Would you add

```
You may need access to dependent pecl libraries, most which can be found by

    sudo add-apt-repository ppa:ondrej/php
```

immediately after 

#### 2.1 Dependencies for Ruby

in README.md?

Best

[README.txt](https://github.com/vteams/open-source-billing/files/977274/README.txt)

**Comment by shahzadtariq-nxb** [comment]
Thanks for your suggestion. It would surely helps people while installing OSB. I am going make this update to README file.

**Comment by RyanHarrigan** [comment]
Okay thank you. I see that it is NOT immediately after the headline

```
*** 2.1 Dependencies for Ruby ***
```

Yet, the inserted text is after 

```
Run the following command to install ruby dependencies:
```

This may be a problem because \
`sudo apt-get update`

is needed after installing a PPA, which is why I recommended to insert it immediately after the headline. Users will need to synchronize their repository lists after adding the PPA. Pleas see the article below for the reason.

https://askubuntu.com/questions/333768/the-purpose-of-updating-after-adding-a-ppa-repository
