### ISSUE TITLE
Discount offered as % or USD when default currency is GBP for company and client

### ISSUE THREAD

**Issue by twobob** [vteams/open-source-billing#60]
Hi.

I get 
![image](https://cloud.githubusercontent.com/assets/915232/26705096/c1eeee28-472b-11e7-927d-79828f449f40.png) despite choosing GBP

Because when I try to run **rake db:seed** I get
```
[DEPRECATION] This gem has been renamed to hashie-forbidden_attributes and will no longer be supported. Please switch to hashie-forbidden_attributes as soon as possible.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
...
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

/home/deeplearning/.rvm/gems/ruby-2.0.0-p648/gems/actionpack-4.1.15/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::PDF
/home/deeplearning/.rvm/gems/ruby-2.0.0-p648/gems/actionpack-4.1.15/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of PDF was here
```

I have checked - they are not nil. they are in fact those values.

I did note that in your installation docs you say to run.

> 3.5 Tables schema and seeding
> **rake db:migrate**
> Loading default values in database
> **rake db:seed**

however that would not complete - at all - until I manually copied config/config.yml.copy to config/config.yml FIRST - are the docs in error? or did my install perhaps go wayward?

Thanks for any light anyone can shed on some steps to get this initially functioning :)

**Comment by twobob** [comment]
So I managed to dredge

/usr/local/src/open-source-billing/config/initializers/config.rb:10:in `<module:CONFIG>': undefined method `[]' for nil:NilClass (NoMethodError)

out of it. by: RAILS_ENV=test bundle exec rails c 

what am I missing?

**Comment by welshcoder** [comment]
Hi,

You are right - the documentation is incorrect, and you should copy `config/config.yml.copy` to `config/config.yml` first, and set up everything in there. It's the only way I got it to work.

As for the discounting issue, I found I had to change `DISCOUNT_TYPE` in `config/initializers/initializers.rb` to change USD to GBP in that dropdown box. I've actually had to make quite a few changes to get GBP or "£" to show in this application. See my comment on Issue #64 for my manual solution to this. 

I hope that helps.

Cheers,
welshcoder
