### ISSUE TITLE
Demo website down

### ISSUE THREAD

**Issue by rivstone** [vteams/open-source-billing#67]
![bug](https://user-images.githubusercontent.com/28851592/32875006-a52f2fd2-cabb-11e7-853d-896460fe67f6.png)
For your kind information,  the following website is down.

http://demo.opensourcebilling.org/

Can u pls up the server?

**Comment by shahzadtariq-nxb** [comment]
Demo site is up and working now. There was server space issue due to which it was not responding

**Comment by rivstone** [comment]
Thank u very much
