### ISSUE TITLE
Server throws error, unable to login in demo

### ISSUE THREAD

**Issue by rivstone** [vteams/open-source-billing#68]
Hi Team,

When I login with default username and password, it throws the error

**The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.**

-Thanks, Jefferson

**Comment by shahzadtariq-nxb** [comment]
Issue has been resolved. Now you login and browse OSB on demo.opensourcebilling.org

**Comment by rivstone** [comment]
Thank u team
