### ISSUE TITLE
Stripe Support

### ISSUE THREAD

**Issue by ciscllc** [vteams/open-source-billing#70]
Hi!

Are there any ideas of supporting stripe in the near future?

**Comment by natemmg** [comment]
Very curious about this, as well.

**Comment by D4V3M0NK** [comment]
Can't agree more - I understand PayPal but Stripe is becoming more and more popular with it's flexible APIs. Would be an excellent additional to this functional billing platform

**Comment by therealrodk** [comment]
Please add Stripe functionality! We have developed a dislike for PayPal and would much prefer to continue using Stripe if we switch to using OSB. Stripe is much easier to code for, for one thing.

**Comment by Promaethius** [comment]
Unless it's a dangling dependency, OSB has had stripe integration for nearly one year. 

https://github.com/vteams/open-source-billing/blob/master/config/application.yml.copy

https://github.com/vteams/open-source-billing/blob/master/Gemfile#L67

**Comment by imranmalik** [comment]
We working on this functionality and would be available in next stable release
