### ISSUE TITLE
null invoice causing problems

### ISSUE THREAD

**Issue by cedarlug** [vteams/open-source-billing#75]
With an updated git, I'm experiencing consistent rendering failures with the link provided in e-mailed invoices to the client.

I am able to create/view/delete/modify/send/print/generate PDFs of invoices, but the link sent to the client in e-mail causes the following error:

```
Started GET "/invoices/preview?inv_id=TDFFd2FHZFRTbVZ3UkVGdU9FTjRNMUpQVEZsWlp6MDlMUzE2TVdReGVrTnBj%250AazFFYW5oNGNDODRZekJYVWxKQlBUMD0tLTdkZjQ3MThhNGQ0NTVjMjFmYWQw%250AMTE1Y2E5NTNhNmM5ZTQ5MTdjYzk=%250A" for ZZZ.227.YYY.XX at 2018-09-05 18:53:31 +0000
Processing by InvoicesController#preview as HTML
  Parameters: {"inv_id"=>"TDFFd2FHZFRTbVZ3UkVGdU9FTjRNMUpQVEZsWlp6MDlMUzE2TVdReGVrTnBj%0AazFFYW5oNGNDODRZekJYVWxKQlBUMD0tLTdkZjQ3MThhNGQ0NTVjMjFmYWQw%0AMTE1Y2E5NTNhNmM5ZTQ5MTdjYzk=%0A"}
  Invoice Load (0.6ms)  SELECT  `invoices`.* FROM `invoices` WHERE `invoices`.`deleted_at` IS NULL AND `invoices`.`id` IS NULL LIMIT 1
  Invoice Load (0.5ms)  SELECT  `invoices`.* FROM `invoices` WHERE (`invoices`.`deleted_at` IS NOT NULL) AND `invoices`.`id` IS NULL LIMIT 1
  Rendered invoices/_show_invoice.erb (7.1ms)
  Rendered invoices/preview.html.erb within layouts/pdf_mode (8.3ms)
Completed 500 Internal Server Error in 15ms (ActiveRecord: 1.0ms)

ActionView::Template::Error (undefined method `encrypted_id' for nil:NilClass):
    10: 
    11:             <%= link_to raw("<i class='material-icons'>picture_as_pdf</i>"),
    12:                         {:controller => 'invoices', :action => 'invoice_pdf',
    13:                          :id => @invoice.encrypted_id, :format => "pdf"},
    14:                         :target => '_blank', title: t('views.common.pdf') %>
    15:             <%= link_to raw("<i class='material-icons'>print</i>"),
    16:                         {:controller => 'invoices', :action => 'invoice_pdf',
  app/views/invoices/_show_invoice.erb:13:in `_app_views_invoices__show_invoice_erb___2073211008026150361_70300413113820'
  app/views/invoices/preview.html.erb:3:in `_app_views_invoices_preview_html_erb__3880540000382134872_70300412280640'
  app/controllers/invoices_controller.rb:83:in `block (2 levels) in preview'
  app/controllers/invoices_controller.rb:82:in `preview`
```
The URL provided to the client is:
```
http://the.billing.site/invoices/preview?inv_id=TDFFd2FHZFRTbVZ3UkVGdU9FTjRNMUpQVEZsWlp6MDlMUzE2TVdReGVrTnBj%0AazFFYW5oNGNDODRZekJYVWxKQlBUMD0tLTdkZjQ3MThhNGQ0NTVjMjFmYWQw%0AMTE1Y2E5NTNhNmM5ZTQ5MTdjYzk=%0A
```

Ubuntu 16.04.5
Physical system (not a vm).

Any suggestions on where to look further for a resolution?
ADVthanksANCE

**Comment by tabish-saleem-nxb** [comment]
This issue can be occurred due to the following two (2) reasons:

1. After sending the new invoice to the client via email, the invoice has been deleted from the database (e.g. phpMyAdmin etc) and then tried to access invoice from email link and error occurred.
2.  After sending the new invoice to the client via email, **encryption_key** has been updated in config/config.yml and error occurred.

**Comment by cedarlug** [comment]
Greatly appreciate your suggestions.

Neither of the above options are present.

The encryption key is unchanged between invoice generation and link access. Further, the invoice is still present in the database and can be otherwise viewed/modified/rendered as PDF/etc.

**Comment by cedarlug** [comment]
To expand on the issue a bit, I just blew away the database and started over with a new client, new invoice, and a new invoice item.  Saved, Recalled, Sent to the client.  The issue persists.

**Comment by cedarlug** [comment]
Installed under Debian stretch.  No problem.

Perhaps an incompatible cryptographic gem in Ubuntu 16?
