### ISSUE TITLE
Add support spanish language.

### ISSUE THREAD

**Issue by nmenag** [vteams/open-source-billing#76]
How can add a new language?, i need traslate to spanish. thanks.

**Comment by nazarhussain** [comment]
You can translate this file https://github.com/vteams/open-source-billing/blob/master/config/locales/en.yml in Spanish as `es.yml` and create a pull request with the change.

**Comment by yuri-val** [comment]
@nmenag Have you already started translating into Spanish?
@nmenag @nazarhussain I can auto translate it with google translator to Spanish, but @nmenag need to check translation and correct it.

**Comment by nmenag** [comment]
@yuri-val I would like to do the PR, but I don't have time.  I am waiting  have free time.

**Comment by yuri-val** [comment]
@nmenag ok, i translate it an left in my [fork](https://github.com/yuri-val/open-source-billing).
when you have free time, look at the translation and correct it. then I'll do the PR. What do you think?

**Comment by nmenag** [comment]
@yuri-val  Of course. I review the traslate

**Comment by nmenag** [comment]
@yuri-val the next week I review the translate.

**Comment by yuri-val** [comment]
@nmenag ok, pls, check this banch https://github.com/yuri-val/open-source-billing/tree/spanish_locale
this https://github.com/yuri-val/open-source-billing/blob/spanish_locale/config/locales/devise.es.yml
and this https://github.com/yuri-val/open-source-billing/blob/spanish_locale/config/locales/es.yml
files

**Comment by nmenag** [comment]
@yuri-val already I did a commit with some corrections, I would like to see a demo in Heroku o similar because I can't  install the project on my computer.  I have a problem with Mysql native extension.

**Comment by yuri-val** [comment]
@nmenag send you via email

**Comment by nmenag** [comment]
@yuri-val an email?, where?

**Comment by yuri-val** [comment]
mailto:nmena.garzon@gmail.com
From your profile

**Comment by nmenag** [comment]
@yuri-val I was reviewing the translate for me is it Ok, I did a new commit for improve some words.

**Comment by nmenag** [comment]
@yuri-val  we can do the PR .

**Comment by yuri-val** [comment]
@nmenag tnx for help
https://github.com/vteams/open-source-billing/pull/83
Wait for owner’s rewinding

**Comment by nmenag** [comment]
resolved #83
