### ISSUE TITLE
Alignment when viewing / printing

### ISSUE THREAD

**Issue by D4V3M0NK** [vteams/open-source-billing#78]
There's an alignment issue when an invoice is viewed or printed, subsequent to being entered. 

Upon entering the invoice, all the line item fields line up correctly under their column titles (Item, Description, Unit cost, Quantity, Tax 1, Tax 2 and Total) but once submitted and then reviewed afterwards in either the normal view, print, or PDF, the line total and quantity both appear under the **Quantity** column heading.
![viewinvoice](https://user-images.githubusercontent.com/7572742/49106378-e726c180-f237-11e8-865e-75b7c5341b79.jpg)

(A line items in my invoices have no taxes, therefore they've been left empty.)

I'm using the latest version as of 11/27/18

**Comment by imranmalik** [comment]
Issue has been fixed and verified in latest release
