### ISSUE TITLE
Invoices PDF logo is not placed

### ISSUE THREAD

**Issue by rennhak** [vteams/open-source-billing#8]
Invoices pdf generation works for me (running currently on guest with Xvfb for wkhtmltopdf). Only problem is that placed image is some placeholder currently, not company logo. If you inspect a draft invoice it looks correctly, but not when outputted to pdf.

Tried with wkhtmltopdf 0.9.9-4 (debian stable) and newest from http://wkhtmltopdf.org/ which is 0.12.0 yielding same issue. I also inspected @invoice.company.logo_url(:thumb) which looks correct, but somehow wkhtmltopdf ignores it.

Makes also no difference if jpg or png is used, you just see a small box with black border, no logo.

Thank you for all your work on this.

**Comment by sarwan-nxb** [comment]
This issue is resolved in release 1.0
