### ISSUE TITLE
Сuts off the fractional part when add new row

### ISSUE THREAD

**Issue by yuri-val** [vteams/open-source-billing#81]
I add some items to Invoice with float qty
![image](https://user-images.githubusercontent.com/15129796/50401863-758c5580-079a-11e9-8a8b-a2072bcad8f9.png)
when i add one more line it cuts off  the fractional part 
![image](https://user-images.githubusercontent.com/15129796/50401902-d3b93880-079a-11e9-9fa7-69573c359106.png)

**Comment by imranmalik** [comment]
Quantity is Integer type and cant hold support floating point values. You need to fill that with proper positive integers only

**Comment by yuri-val** [comment]
@imranmalik but if we look at `schema.rb` https://github.com/vteams/open-source-billing/blob/54708c2247109b6b8c876162ba68072d4070bb73/db/schema.rb#L265 we'll see that it could be  `precision: 10, scale: 2` , isn't it?
