### ISSUE TITLE
check in `Gemfile.lock` and `.ruby-version`

### ISSUE THREAD

**Issue by alexanderadam** [vteams/open-source-billing#87]
Hi @mshahzadtariq,

[`Gemfile.lock`](https://stackoverflow.com/a/4151540/900545) and `.ruby-version` should be integrated in a modern project.
And it would even be better if there would be a `Dockerfile` with [an official image](https://github.com/vteams/open-source-billing/issues/58) ([doc](https://docs.docker.com/docker-hub/official_images/#creating-an-official-image)).

Thank you for your work!

**Comment by shahzadtariq-nxb** [comment]
@alexanderadam We have noted down your suggestions and would integrate lock and version files in next release. Docker image is also in development queue and would be released very soon.

**Comment by mshahzadtariq** [comment]
@alexanderadam .ruby-version file is used to specify ruby version used with Rails project. 
Alternate approach is to specify ruby version directly in Gemfile and we are using this approach and due to this i have closed this issue.

**Comment by alexanderadam** [comment]
@mshahzadtariq your response is a bit problematic:

1. This issue is about **two** files: `Gemfile.lock` and `.ruby-version`. And there's no reason why someone should _not_ checkin `Gemfile.lock` except if you want to provoke dependency mismatches. Please read [why it is a good idea to check in `Gemfile.lock` in a Ruby / RoR project](https://bundler.io/v1.3/rationale.html#checking-your-code-into-version-control).

> @alexanderadam .ruby-version file is used to specify Ruby version used with Rails project.
> Alternate approach is to specify Ruby version directly in Gemfile and we are using this approach and due to this i have closed this issue.
2. It's not an alternative approach. Let me explain: since around five years ago, Ruby version managers became popular. This is true even nowadays. People usually use Docker ([see also issue 58](https://github.com/vteams/open-source-billing/issues/58)) and/or a Ruby version manager. Popular version managers are `rbenv`, `rvm` and `chruby`. All of them support the `.ruby-version` file but setting the Ruby version from `Gemfile` is not generally possible (see for example [this rbenv issue](https://github.com/rbenv/rbenv/issues/223#issuecomment-525490880) or [this chruby issue](https://github.com/postmodern/chruby/issues/313)). If you have to insist on the definition within the `Gemfile` you could set it in the `.ruby-version` file and load it in the `Gemfile` with

```ruby
# Gemfile
source 'https://rubygems.org'
ruby File.read('.ruby-version').chomp
gem 'rails', '~> 4.2.7.1'
…
```

**Comment by alexanderadam** [comment]
[The `Gemfile.lock` was just pushed by the maintainer(s)](https://github.com/vteams/open-source-billing/commit/24b0c6c634483e884c42440fd77e5a8731f98ba0#diff-e79a60dc6b85309ae70a6ea8261eaf95). :tada:
