### ISSUE TITLE
Compatibility Issues with bundler in Ubuntu 18 (FIX)

### ISSUE THREAD

**Issue by homepods** [vteams/open-source-billing#88]
`Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    osb_api was resolved to 0.0.1, which depends on
      rails (~> 4.2.7.1) was resolved to 4.2.7.1, which depends on
        bundler (< 2.0, >= 1.3.0)

**Comment by homepods** [comment]
you have to 
#gem uninstall bundler 
#gem instll bundler -v 1.9

**Comment by alexanderadam** [comment]
I don't think the people that are developing **open-source-billing** are actually watching for issues here. Your issue for example would be avoidable [with a `Dockerfile`](https://github.com/vteams/open-source-billing/issues/58) that uses and shows the installation steps and its dependencies.

Also it's common to check in [the files `Gemfile.lock` and `.ruby-version`](https://github.com/vteams/open-source-billing/issues/87).

I think OpenSourceBilling is great but the, somehow closed, development process is probably one of the reasons why it's not popular.

**Comment by shahzadtariq-nxb** [comment]
@alexanderadam Thank you for your valuable feedback. In fact we are working on lot of improvements and feature development. Dockerfile is already in our road map and shall release that very soon.

**Comment by alexanderadam** [comment]
@shahzadtariq-nxb thank you for responding. Why are you closing those issues (i.e. this or #87)  if they aren't fixed yet? Shouldn't they be closed _after_ they are fixed?
