### ISSUE TITLE
Spanish translation missing

### ISSUE THREAD

**Issue by asanabria27** [vteams/open-source-billing#89]
Hi, I would like to help with the Spanish translation and with bug fixes. How is the workflow, do I need to create a branch and do pull request?

**Comment by asanabria27** [comment]
@mshahzadtariq

**Comment by shahzadtariq-nxb** [comment]
@asanabria27 you can contribute by:
1. Fork this repository
2. Create a new feature branch
3. Add spanish translation yml file and any other bug fixes
4. Push you changes
5. Create pull request
