### ISSUE TITLE
⚠️ Please don't close unsolved issues! ⚠️

### ISSUE THREAD

**Issue by alexanderadam** [vteams/open-source-billing#90]
# ⚠️ Please don't close unsolved issues! ⚠️

I don't know why you are doing this but your users cannot track issues if you just close them!

Please _reopen_ issues like

* #88 
* ~~#87~~ finally solved with [this commit](https://github.com/vteams/open-source-billing/commit/24b0c6c634483e884c42440fd77e5a8731f98ba0#diff-e79a60dc6b85309ae70a6ea8261eaf95)
* #82 
* #81 
* #72
* ~~#58~~ finally solved with [this commit](https://github.com/vteams/open-source-billing/commit/24b0c6c634483e884c42440fd77e5a8731f98ba0#diff-4e5e90c6228fd48698d074241c2ba760)

etc.

Because those issues are **not** solved at the moment.
You should close those issues _after_ you solved them.

**Comment by shahzadtariq-nxb** [comment]
Reported Issues are solved and verified

**Comment by alexanderadam** [comment]
That's not true. You just closed them without fixing them. :wink: 

Check those three of the list:

* #82 - about updating the unsupported(!) depedencies [Ruby 2.3.7](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/) and [Rails 4.2.7.1](https://stackoverflow.com/questions/43050213/ruby-on-rails-4-2-end-of-life)
* #81 - you didn't even answer on [the last comment](https://github.com/vteams/open-source-billing/issues/81#issuecomment-507783153)
* #72 - responsiveness for small mobile devices is not fixed, right?
