### ISSUE TITLE
Status of API Availability

### ISSUE THREAD

**Issue by teh-random-name** [vteams/open-source-billing#94]
Ref #62
Trying to find documentation regarding an API, this issue stated the API was in alpha but that was back in 2017.

Is there a dot version or ETA date for when this becomes available?

**Comment by shahzadtariq-nxb** [comment]
You can find API docs at following url of your installation

/api/docs

e.g. if you are running OSB on your localhost server at 3000 port, API docs can be accessed at 

http://localhost:3000/api/docs
